### ISSUE TITLE
estimate_joint_error function is missing in Utils.py

### ISSUE THREAD

**Issue by Vittorio-Caggiano** [aikkala/O2MConverter#1]
Hi, 

great project!

I am trying to run the scripts to reproduce you results but the function `estimate_joint_error` function is missing in `Utils.py`

https://github.com/aikkala/O2MConverter/blob/3ab6cc06e0b00c8e39634080fa2fa89190c867f4/tests/process_test_runs.py#L39

**Comment by aikkala** [comment]
Hi Vittorio,

I'm glad to hear you're interested in this project. The codebase is a little bit outdated, apologies for that, I'll try update all code once I have some spare time. This particular function `estimate_joint_error` is now known as `estimate_error` in the Utils.py. All input arguments are the same, except instead of input parameter `joint_names` you should use `target_names`.

**Comment by Vittorio-Caggiano** [comment]
Hi Alexi, 

thanks, it works now.
